### ISSUE TITLE
Fail2Ban addition

### ISSUE THREAD

**Issue by Condorello** [TECH7Fox/sip-hass-docs#13]
Hi, very nice works. Finally i can manage my Dahua fully local.
But it's need to expose sip and rtp ports for answer the doorbell from outside. What about adding a fail2ban inside the container?

**Comment by TECH7Fox** [comment]
Sorry for the late reply, this isn't the correct place for this issue.

Adding fail2ban into the add-on itself adds some issues. You could however use fail2ban seperatly and point the asterisk logs to it.

Related issues:
* https://github.com/TECH7Fox/asterisk-hass-addons/issues/51
* https://github.com/TECH7Fox/asterisk-hass-addons/issues/178
