### ISSUE TITLE
Question about the requirement of needing a separate user per device

### ISSUE THREAD

**Issue by cibernox** [TECH7Fox/sip-hass-docs#21]
Hi! First of all, I don't know how I missed this addon/integration until now! Stellar work! 
I did look if someone had done something similar when I got my dahua doorbell but nothing came up in 2020. I fact I did try running asterisk myself and did some testing but I abandoned it for lack of time and SIP knowledge in general. 
Now I'm going to try this. For now I'm trying from device to device before risking changing the SIP server on my dahua VTO/VTH duo. I did manage to make an audio call browser to browser already!

One thing that has raised questions is the need for different users for every device. The reason being that most people will use HA in their browser, their mobile app and sometimes a wall mounted tablet, and often creating different users is rather inconvenient since much of your UI might be user-customized. And when I call someone, I'd expect them to receive that call on any/all their devices.
I wonder what the reason for that limitation is, and if that could be configured at the card level or at the integration level.

Thanks!

**Comment by TECH7Fox** [comment]
Hi @cibernox,

The different users is so you can call to others for if you have wall mounted tablets like a intercom system.

For phone and desktop for the same person you don't need to make multiple users if you don't want to call between them.

And If you don't want to use persons at all, you can use the backup extension and only set custom extensions in the card.

Did that answer your questions?

**Comment by TECH7Fox** [comment]
Closing for now. Please reopen if you still got questions, or ask in the discord server.
