### ISSUE TITLE
trunk to my main asterisk server to call out. /config/asterisk/default/pjsip_custom.conf removed

### ISSUE THREAD

**Issue by Bram-diederik** [TECH7Fox/sip-hass-docs#23]
I want to make a sip card that can dail out using my main asterisk system.

I think i need to setup a trunk in /config/asterisk/default/pjsip_custom.conf 

but /config/asterisk/default/pjsip_custom.conf is purged at every restart of the addon.

**Comment by BitterRose** [comment]
How did you solved this problem?
