### ISSUE TITLE
How to have both park and dial for doorbell

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/sip-hass-docs#9]
In my case I have:

1. One tablet, always on, ready to receive calls at all time
2. Many Android devices, like my phone, which will not be always on

And I wanted to mix both the parking (so that I can send an actionable notification to my phones), but also call the tablet so that it rings normally.

Any tips?

**Comment by TECH7Fox** [comment]
Fabio made a while loop so it keeps trying until someone picks up. This way it works for both registered and unregistered endpoints.

**Comment by TECH7Fox** [comment]
Here is a example:
```
exten => s,1,NoOp() 
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ])
 same => n,Set(DIALGROUP(mygroup,add)=PJSIP/6001) 
 same => n,Set(DIALGROUP(mygroup,add)=PJSIP/100) 
 same => n,Dial(${DIALGROUP(mygroup)},60)
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,GotoIf($["${HANGUP_CAUSE}" == "0"]?exitdialplan)  
 same => n,Wait(1) 
 same => n,SET(COUNT=$[${COUNT} + 1]
 same => n,EndWhile()
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE}) 
 same => n,Hangup()
```

**Comment by felipecrs** [comment]
This is really interesting. Thanks a lot! Will let you know how it works when I try it.
